version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#
#  db:
#    image: "postgres:13"
#    environment:
#      POSTGRES_DB: "fastapi_db"
#      POSTGRES_USER: "fastapi_user"
#      POSTGRES_PASSWORD: "fastapi_password"
#    ports:
#      - "5432:5432"
